// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezjprxiiohdibrxrmdoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6anByeGlpb2hkaWJyeHJtZG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDA2NDQsImV4cCI6MjA2NjE3NjY0NH0.eAufFbzyTb7kbmfaNHt-mUaHEk0fEiXRinIjZaZNA_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);